- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Filter installed expected packages with versions
  ansible.builtin.set_fact:
    installed_packages: >-
      {{
        dict(
          (pkg, ansible_facts.packages[pkg][0])
          for pkg in expected_packages
          if pkg in ansible_facts.packages
        )
      }}

- name: Display installed expected packages with versions
  ansible.builtin.debug:
    msg: >-
      Installed expected packages and their versions:
      {% for pkg, version in installed_packages.items() %}
      - {{ pkg }}: {{ version }}
      {% endfor %}
  when: installed_packages | length > 0

- name: Display message if no expected packages are installed
  ansible.builtin.debug:
    msg: "None of the expected packages are installed."
  when: installed_packages | length == 0